### ISSUE TITLE
[BUG] Artemis won't unload wrong device layouts

### ISSUE THREAD

**Issue by Cheerpipe** [Artemis-RGB/Artemis#616]
If a wrong device layout is loaded, it won't be unloaded when reseting/removing layout setting. Device LED IDs list will also be empty until artemis is restarted.

Steps to reproduce:

1.- Load a good layout. All works as expected.
2.- Load a wrong layout (with wrong leds Ids). Layout is loaded but led ids will dissapear.
3.- Load the good layout again. Led ids list is still empty.
4.- Remove the layout. Layout is still loaded and led ids is still empty.

**Comment by SpoinkyNL** [comment]
Fixed in fe933f60e8f7290fb400dcddef754c2f901f9416 I think, please try it out

**Comment by Cheerpipe** [comment]
It still happens

https://media.giphy.com/media/b9aND66ajuIQn4u6gg/giphy.gif

**Comment by SpoinkyNL** [comment]
Can you ZIP up the layouts so I can test myself?

**Comment by Cheerpipe** [comment]
Sure.

I did some test with logitech device provider and layouts are loading/unloading/re-loading ok for my keyboard. ¿? Might it be a bug in the device provider ? (OpenRGB)

[Layouts.zip](https://github.com/Artemis-RGB/Artemis/files/6638747/Layouts.zip)

**Comment by Cheerpipe** [comment]
More weird behavior with OpenRGB. Idk if it is a provider or artemis bug.

https://user-images.githubusercontent.com/972765/121712625-f1cd9d00-caa9-11eb-890a-7c98b0ddc294.mp4

**Comment by SpoinkyNL** [comment]
How is it now? I noticed an issue with how the Logitech device provider was unloaded and fixed that

**Comment by Cheerpipe** [comment]
Device is unloading/loading ok. The problem appears to be more on the Artemis side. I did an additional test changing layout and reloading device plugin device provide feature manually and it worked.
 
Uploaded a video in discord (PD: It also crashed one time)

**Comment by SpoinkyNL** [comment]
I made some more improvements but I can't reproduce this with the layouts you sent me. Are you sure they are the 'bad' ones? They all contain LEDs

**Comment by SpoinkyNL** [comment]
Any idue what the status is on this @Cheerpipe?

**Comment by Cheerpipe** [comment]
Cant get it to work in a consistent way.

https://www.youtube.com/watch?v=V0I0kbM7VtY

1.- It works the first time but layout is not refreshed.
2.- It make my device disappears the second time i remove a layout

I can't disable device provider (DMX) after the second time by the way

https://user-images.githubusercontent.com/972765/130829005-cf171dae-cd4e-4a49-87e5-43ebbf58d262.mp4
